### ISSUE TITLE
Task 1 review

### ISSUE THREAD

**Issue by nadejdashed** [mohanakrishnag/Native-JS#3]
Without comments. Nice work:
- Basic_Mathematical_Operations
- Opposite number. Could be also done as return -number
- Printing_Array_elements_with_Comma_delimiters

Please improve:
- Calculating_with_Functions. Function return operation ? operation(0) : 0 repeats except the number in it. Please combine them to avoid duplication.
- Transportation_on_vacation.
1) Betteer to use one return statement. 
2) Extra check day < 7
- Finish all other tasks

**Comment by mohanakrishnag** [comment]
@nadejdashed I have implemented you review comments and completed the pending tasks in HW#1. Please review

**Comment by nadejdashed** [comment]
@mohanakrishnag, cost = 0 is not necessary define, because you overwrite it on the next line. Also put the declare it on the next line for readability.

**Comment by nadejdashed** [comment]
@mohanakrishnag, 
- Get-the-middle-character.js please use single return, look at duplication. Do it on all your code.
- Partition-on.js please think about other implementation of thi task. Now you create 2 array, then merge them. It take extra memory. Could it be done easier without creation new arrays?

**Comment by mohanakrishnag** [comment]
@nadejdashed 
- Refactored the code in Transportation_on_vacation.js as per the comments provided.
- Refactored the code in Get-the-middle-character.js with single return statement.
- And regarding the Partition-on.js, As you suggested instead of creating 2 new arrays i am trying to swap the position of elements by with odd and even numbers, but im failing to achieve the output. I will discuss with you on this.

**Comment by nadejdashed** [comment]
@mohanakrishnag, 
- Get-the-middle-character.js, middleIndex could be 1.5 value
